# Add labels based on file patterns

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'
          - '**/doc.go'
          - '.github/ISSUE_TEMPLATE/**'

github:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

gh-actions:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'

codeql:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/codeql/**'
          - '.github/workflows/codeql.yml'

issue-templates:
  - changed-files:
      - any-glob-to-any-file: '.github/ISSUE_TEMPLATE/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_test.go'
          - 'test/**'
          - 'internal/testutils/**'

benchmarks:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_bench_test.go'
          - '**/*_benchmark_test.go'

# Core components
composer:
  - changed-files:
      - any-glob-to-any-file: 'pkg/composer/**'

connection:
  - changed-files:
      - any-glob-to-any-file: 'pkg/connection/**'

commands:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/**'

executor:
  - changed-files:
      - any-glob-to-any-file: 'pkg/document/executor/**'

schema:
  - changed-files:
      - any-glob-to-any-file: 'pkg/document/schema/**'

builder:
  - changed-files:
      - any-glob-to-any-file: 'pkg/document/builder/**'

graphics:
  - changed-files:
      - any-glob-to-any-file: 'pkg/graphics/**'

qr-image:
  - changed-files:
      - any-glob-to-any-file: 'pkg/graphics/qr.go'

profile:
  - changed-files:
      - any-glob-to-any-file: 'pkg/profile/**'

printer:
  - changed-files:
      - any-glob-to-any-file: 'pkg/printer/**'

tables:
  - changed-files:
      - any-glob-to-any-file: 'pkg/tables/**'

# ESC/POS specific components
barcode:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/barcode/**'

bitimage:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/bitimage/**'

character:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/character/**'

common:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/common/**'

linespacing:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/linespacing/**'

mechanismcontrol:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/mechanismcontrol/**'

print:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/print/**'

printposition:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/printposition/**'

qrcode:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/qrcode/**'

emulator:
  - changed-files:
      - any-glob-to-any-file: 'pkg/emulator/**'

constants:
  - changed-files:
      - any-glob-to-any-file: 'pkg/constants/**'

# Other categories
windows:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_windows.go'
          - 'pkg/connection/windows/**'

linux:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_linux.go'
          - 'pkg/connection/linux/**'

macos:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_darwin.go'
          - 'pkg/connection/darwin/**'

examples:
  - changed-files:
      - any-glob-to-any-file: 'examples/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'go.mod'
          - 'go.sum'
          - 'package.json'
          - 'package-lock.json'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - '*.yml'
          - '*.yaml'
          - '*.json'
          - '.golangci.yml'
          - '.codecov.yml'
          - 'Makefile'

api:
  - changed-files:
      - any-glob-to-any-file:
          - 'api/**'
          - 'api/v1/**'

security:
  - changed-files:
      - any-glob-to-any-file:
          - '**/SECURITY.md'
          - '.github/workflows/codeql.yml'
          - '.github/workflows/security.yml'