# Add labels based on file patterns

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'
          - '**/doc.go'
          - 'ISSUE_TEMPLATE/**'

github:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

gh-actions:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_test.go'
          - 'test/**'
          - 'internal/testutils/**'

# Core components
composer:
  - changed-files:
      - any-glob-to-any-file: 'pkg/composer/**'

connection:
  - changed-files:
      - any-glob-to-any-file: 'pkg/connection/**'

commands:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/**'

executor:
  - changed-files:
      - any-glob-to-any-file: 'pkg/document/executor/**'

schema:
  - changed-files:
      - any-glob-to-any-file: 'pkg/document/schema/**'

builder:
  - changed-files:
      - any-glob-to-any-file: 'pkg/document/builder/**'

graphics:
  - changed-files:
      - any-glob-to-any-file: 'pkg/graphics/**'

qr-image:
  - changed-files:
      - any-glob-to-any-file: 'pkg/graphics/qr.go'

profile:
  - changed-files:
      - any-glob-to-any-file: 'pkg/profile/**'

printer:
  - changed-files:
      - any-glob-to-any-file: 'pkg/printer/**'

tables:
  - changed-files:
      - any-glob-to-any-file: 'pkg/tables/**'

# ESC/POS specific components
barcode:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/barcode/**'

bitimage:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/bitimage/**'

character:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/character/**'

common:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/common/**'

linespacing:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/linespacing/**'

mechanismcontrol:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/mechanismcontrol/**'

print:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/print/**'

printposition:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/printposition/**'

qrcode:
  - changed-files:
      - any-glob-to-any-file: 'pkg/commands/qrcode/**'

emulator:
  - changed-files:
      - any-glob-to-any-file: 'pkg/emulator/**'

# Other categories
windows:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_windows.go'
          - 'pkg/connection/windows/**'

examples:
  - changed-files:
      - any-glob-to-any-file: 'examples/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'go.mod'
          - 'go.sum'
          - 'package.json'
          - 'package-lock.json'