# golangci-lint configuration for Poster
# Reference: https://golangci-lint.run/usage/configuration/

version: "2"
run:
  timeout: 5m  # 5 minutos es suficiente
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - examples
    - testdata
  skip-files:
    - ".*_test.go$"  # Skip test files for some linters
  modules-download-mode: readonly

output:
  formats:
    format: colored-line-number
    print-issued-lines: true
    print-linter-name: true
    sort-results: true

linters:
  # Solo habilitar los esenciales
  enable:
    # Critical - Must pass
    - errcheck       # Check for unchecked errors
    - govet          # Vet examines Go source code
    - staticcheck    # Advanced Go linter
    - ineffassign    # Detect ineffectual assignments
    - gosec          # Security problems
    - unused         # Check for unused code

    # Code Quality
    - gocyclo        # Cyclomatic complexity
    - gocritic       # Most opinionated linter
    - unparam        # Unused function parameters
    - revive         # Fast, configurable, extensible

    # Best Practices
    - prealloc       # Slice preallocation
    - bodyclose      # Check HTTP body is closed
    - goconst        # Repeated strings that could be constants
    - unconvert      # Remove unnecessary type conversions
    # - misspell       # Spelling mistakes (not for now)
    - nolintlint     # Ensure nolint directives are valid

    # Error Handling
    - errorlint      # Error wrapping issues
    - errname        # Error naming conventions

    # Code Clarity
    # - godot          # Check comments end in period
    - whitespace     # Whitespace issues

    # Performance (optional but recommended)
    - noctx          # HTTP requests without context

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*os.File).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close

  govet:
    enable-all: true
    disable:
      - shadow  # Too strict for this project
      - fieldalignment  # Performance optimization, not critical

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - unnamedResult  # We use named returns intentionally

  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: error-naming
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (errcheck handles this)
      - G304  # File path provided as input (needed for file operations)

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  nolintlint:
    allow-unused: false
    allow-no-explanation: [ ]
    require-explanation: true
    require-specific: true

  whitespace:
    multi-if: true
    multi-func: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - gosec
        - unparam
        - goconst

    # Exclude some checks from examples
    - path: examples/
      linters:
        - errcheck
        - gosec
        - gocritic

    # Known false positives
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Allow TODO/FIXME comments in development
    - text: "Line contains TODO/BUG/FIXME"
      linters:
        - godot

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

severity:
  default-severity: error
  case-sensitive: false