# https://taskfile.dev

version: '3'

vars:
  POSTER: ./bin/poster.exe
  TEST_FLAGS: -coverprofile=coverage.txt -covermode=atomic
  LINT_FLAGS: --timeout=5m
  BANNER: |
    ╔══════════════════════════════════════════════════════════╗
    ║                                                          ║
    ║   ██████╗  ██████╗ ███████╗████████╗███████╗██████╗      ║
    ║   ██╔══██╗██╔═══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗     ║
    ║   ██████╔╝██║   ██║███████╗   ██║   █████╗  ██████╔╝     ║
    ║   ██╔═══╝ ██║   ██║╚════██║   ██║   ██╔══╝  ██╔══██╗     ║
    ║   ██║     ╚██████╔╝███████║   ██║   ███████╗██║  ██║     ║
    ║   ╚═╝      ╚═════╝ ╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝     ║
    ║                                                          ║
    ║                  The POS daemon for Go                   ║
    ║                  ESCPOS · ZPL · Scale                    ║
    ║           Serial · USB · Network · Bluetooth             ║
    ║                                                          ║
    ╚══════════════════════════════════════════════════════════╝

includes:
  barcode:
    taskfile: ./pkg/commands/barcode/Taskfile.yml
    dir: ./pkg/commands/barcode
    aliases:
      - bc
  bitimage:
    taskfile: ./pkg/commands/bitimage/Taskfile.yml
    dir: ./pkg/commands/bitimage
    aliases:
      - bi
  character:
    taskfile: ./pkg/commands/character/Taskfile.yml
    dir: ./pkg/commands/character
    aliases:
      - ch
  linespacing:
    taskfile: ./pkg/commands/linespacing/Taskfile.yml
    dir: ./pkg/commands/linespacing
    aliases:
      - ls
  mechanismcontrol:
    taskfile: ./pkg/commands/mechanismcontrol/Taskfile.yml
    dir: ./pkg/commands/mechanismcontrol
    aliases:
      - mc
  print:
    taskfile: ./pkg/commands/print/Taskfile.yml
    dir: ./pkg/commands/print
    aliases:
      - pr
  printposition:
    taskfile: ./pkg/commands/printposition/Taskfile.yml
    dir: ./pkg/commands/printposition
    aliases:
      - pp
  qrcode:
    taskfile: ./pkg/commands/qrcode/Taskfile.yml
    dir: ./pkg/commands/qrcode
    aliases:
      - qr
  common:
    taskfile: ./pkg/commands/common/Taskfile.yml
    dir: ./pkg/commands/common
    aliases:
      - sh

tasks:
  default:
    cmds:
      - echo "{{.BANNER}}"
    silent: true
  build:
    deps:
      - test
      - lint
    cmds:
      - echo "Building the project..."
      - go build -o ./bin/poster.exe ./cmd/poster
  lint:
    cmds:
      - echo "Running linters..."
      - golangci-lint run {{.LINT_FLAGS}}
  test:
    cmds:
      - echo "Running all tests in detail..."
      - go test {{.TEST_FLAGS}} ./pkg/...
  deps:
    cmds:
      - echo "Tidying and downloading dependencies..."
      - go mod tidy
      - go mod download
  poster:
    desc: Procesa un archivo existente
    # Requiere que se pase un argumento Y que el archivo exista
    preconditions:
      - sh: test -f {{.CLI_ARGS | q}}
        msg: "El archivo '{{.CLI_ARGS}}' no existe o no se especificó."
    cmds:
      - "{{.POSTER}} {{.CLI_ARGS | q}}"