# https://taskfile.dev

version: '3'

vars:
  TEST_FLAGS: -coverprofile=coverage.txt -covermode=atomic
  LINT_FLAGS: --timeout=5m
  BANNER: |
    ╔══════════════════════════════════════════════════════════╗
    ║                                                          ║
    ║   ██████╗  ██████╗ ███████╗████████╗███████╗██████╗      ║
    ║   ██╔══██╗██╔═══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗     ║
    ║   ██████╔╝██║   ██║███████╗   ██║   █████╗  ██████╔╝     ║
    ║   ██╔═══╝ ██║   ██║╚════██║   ██║   ██╔══╝  ██╔══██╗     ║
    ║   ██║     ╚██████╔╝███████║   ██║   ███████╗██║  ██║     ║
    ║   ╚═╝      ╚═════╝ ╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝     ║
    ║                                                          ║
    ║                  The POS daemon for Go                   ║
    ║                  ESCPOS · ZPL · Scale                    ║
    ║           Serial · USB · Network · Bluetooth             ║
    ║                                                          ║
    ╚══════════════════════════════════════════════════════════╝

includes:
  barcode:
    taskfile: ./pkg/commands/barcode/Taskfile.yml
    dir: ./pkg/commands/barcode
    aliases:
      - bc
  bitimage:
    taskfile: ./pkg/commands/bitimage/Taskfile.yml
    dir: ./pkg/commands/bitimage
    aliases:
      - bi
  character:
    taskfile: ./pkg/commands/character/Taskfile.yml
    dir: ./pkg/commands/character
    aliases:
      - ch
  linespacing:
    taskfile: ./pkg/commands/linespacing/Taskfile.yml
    dir: ./pkg/commands/linespacing
    aliases:
      - ls
  mechanismcontrol:
    taskfile: ./pkg/commands/mechanismcontrol/Taskfile.yml
    dir: ./pkg/commands/mechanismcontrol
    aliases:
      - mc
  print:
    taskfile: ./pkg/commands/print/Taskfile.yml
    dir: ./pkg/commands/print
    aliases:
      - pr
  printposition:
    taskfile: ./pkg/commands/printposition/Taskfile.yml
    dir: ./pkg/commands/printposition
    aliases:
      - pp
  qrcode:
    taskfile: ./pkg/commands/qrcode/Taskfile.yml
    dir: ./pkg/commands/qrcode
    aliases:
      - qr
  common:
    taskfile: ./pkg/commands/common/Taskfile.yml
    dir: ./pkg/commands/common
    aliases:
      - sh
  integration-tests:
    taskfile: ./test/Taskfile.yml
    dir: ./test
    aliases:
      - itest
tasks:
  default:
    cmds:
      - echo "{{.BANNER}}"
    silent: true
  build:
    deps:
      - test
      - lint
    cmds:
      - echo "Building the project..."
      - go build -o poster.exe ./cmd/poster
  lint:
    cmds:
      - echo "Running linters..."
      - golangci-lint run {{.LINT_FLAGS}}
  test:
    cmds:
      - echo "Running all tests in detail..."
      - go test {{.TEST_FLAGS}} ./...
  deps:
    cmds:
      - echo "Tidying and downloading dependencies..."
      - go mod tidy
      - go mod download