# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - echo "Running common tests..."
      - go test
  lint:
    cmds:
      - echo "Running common linters..."
      - golangci-lint run